app = "uek-planzajec-v2"
primary_region = "waw"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 3_000
min_machines_running = 0
processes = [ "app" ]

[[vm]]
size = "shared-cpu-1x"

[metrics]
port = 3_000
path = "/metrics"